"""Rebuild editable point/line/box geometry with the current shared fonts/colors.
Numeric continuous panels are regenerated by charts.py and embedded as PDFs.
No old finished figure is copied or rasterized into a candidate.
"""
from pathlib import Path
import json,re,shutil,fitz
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'build.sh').exists())
OUT=Path(__file__).resolve().parent
ARCHIVE=json.loads((OUT/'archive.json').read_text())
def destination(key):return ROOT/ARCHIVE[key]['folder']
scope=json.loads((OUT/'scope.json').read_text())['figures']
mixed={'models-discriminative-generative','models-linear-nonlinear','trust-calibration-discrimination','trust-global-local-explanation','trust-feature-attribution','trust-conformal-construction','trust-dp-neighbors'}
pure_data={Path(f['source'][0]).stem for f in scope if f['classification']=='data'}|{'learning-theory-uniform-convergence'}
depout=OUT/'dependencies';depout.mkdir(exist_ok=True)
for name in ['basics-r5-symbols','trust-vector-symbols','trust-vector-icons']:
    src=next((OUT/'facts/figures/02-foundations').rglob(name+'.tex'))
    text=src.read_text().replace('B5Yellow}{FigureYellow','B5Yellow}{LancetGreen')
    (depout/(name+'.tex')).write_text(text)

def rel(path):return str(path.relative_to(ROOT))
def panel(key):return rel(destination(key)/(key+'.pdf'))
def cleaned(s):
    s=s.replace('\\bfseries','\\mdseries')
    s=re.sub(r'\\input\{figures/02-foundations/[^{}]*/(basics-r5-symbols|trust-vector-symbols|trust-vector-icons)(?:\.tex)?\}',lambda m:'\\input{'+rel(depout/(m[1]+'.tex'))+'}',s)
    s=s.replace('\\definecolor{B7GreenFill}{HTML}{E8F0E8}','\\colorlet{B7GreenFill}{LancetGreen!12!white}')
    s=s.replace('foundation note/.append style={font=\\figurefont','foundation note/.append style={font=\\FigureNoteFont')
    return s

records=[]
for f in scope:
    key=Path(f['source'][0]).stem
    if key in pure_data and key not in mixed:continue
    s=(destination(key)/'baseline-source.tex').read_text()
    route='TikZ'
    if key=='models-linear-nonlinear':
        start=s.index('  \\foreach \\xshift/\\title in {0/线性 SVM')
        geometry=s[start:s.rfind('\\end{tikzpicture}')]
        s='\\begin{tikzpicture}[foundation picture]\n\\node[inner sep=0pt] at (44,80) {\\includegraphics[width=112mm]{'+panel(key)+'}};\n'+geometry+'\\end{tikzpicture}\n'
    elif key=='models-discriminative-generative':
        # Charts occupy the left column; exact score/Bayes calculation is a
        # separate discrete mail example, not a sample of these Gaussians.
        s=r'''\begin{tikzpicture}[foundation picture,font=\figurefont\fontsize{8.5}{11}\selectfont]
\path[use as bounding box] (0,-5) rectangle(169,101);
\node[inner sep=0pt] at (34,49) {\includegraphics[width=65mm]{PANEL}};
\node[anchor=west] at (72,96) {判别式：直接估计};
\node[foundation model,minimum width=28mm] (s) at (84,75) {$s=f_\theta(\bm x)$\\$s=\ln3$};
\node[foundation model,minimum width=17mm] (sig) at (119,75) {$\sigma(s)$};
\node[foundation output,minimum width=28mm] (o) at (153,75) {$p_1=0.75$\\$p_0=0.25$};
\draw[foundation flow] (s)--(sig);\draw[foundation flow] (sig)--(o);
\node[anchor=west] at (72,47) {生成式：联合概率再归一化};
\node[foundation node,fill=FigureRedFill,minimum width=39mm] (j1) at (91,30) {$y=1$：$0.2\times0.12=0.024$};
\node[foundation node,fill=FigureBlueFill,minimum width=39mm] (j0) at (91,10) {$y=0$：$0.8\times0.01=0.008$};
\node[foundation model,minimum width=15mm] (n) at (126,20) {$\div0.032$};
\node[foundation output,minimum width=24mm] (g) at (156,20) {$p_1=0.75$\\$p_0=0.25$};
\draw[foundation flow] (j1.east)--(115,30)--(n.north);\draw[foundation flow] (j0.east)--(115,10)--(n.south);\draw[foundation flow] (n)--(g);
\end{tikzpicture}'''.replace('PANEL',panel(key))
    elif key=='trust-calibration-discrimination':
        s=r'''\begin{tikzpicture}[foundation picture]
\path[use as bounding box] (0,0) rectangle(169,68);
\node[inner sep=0pt] at (39,34) {\includegraphics[width=78mm]{PANEL}};
\node at (113,58) {$\pi_1=0.2$};\node at (150,58) {$\pi_2=0.8$};
\node[anchor=east] at (94,40) {常数};\node[anchor=east] at (94,20) {分组};
\foreach \x in {113,150}{\node[foundation input,minimum width=29mm] at (\x,40) {$p=0.5$};}
\node[foundation output,minimum width=29mm] at (113,20) {$p=0.2$};
\node[foundation output,minimum width=29mm] at (150,20) {$p=0.8$};
\end{tikzpicture}'''.replace('PANEL',panel(key))
    elif key=='trust-global-local-explanation':
        s=s[:s.index(' \\draw[foundation axis')].replace('(0,0) rectangle (110,52)','(0,-5) rectangle (112,60)').replace(' \\node at (83,46) {当前邮件$(1,1)$};','')+r''' \node[inner sep=0pt] at (82,23) {\includegraphics[width=57mm]{PANEL}};
\node at (82,55) {当前邮件$(1,1)$};
\end{tikzpicture}'''.replace('PANEL',panel(key))
    elif key=='trust-feature-attribution':
        s=s[:s.index(' \\draw[foundation axis]')].replace('rectangle(110,71)','rectangle(119,71)')
        s=re.sub(r' \\draw\[foundation flow,draw=Figure(?:Blue|Red)\].*?;\n','',s)+r''' \node[inner sep=0pt] at (88,36) {\includegraphics[width=57mm]{PANEL}};
\draw[foundation flow,draw=FigureBlue] (49,42.5)--(56,42.5)--(56,48)--(62,48);
\draw[foundation flow,draw=FigureRed] (49,31.5)--(57,31.5)--(57,30)--(62,30);
\end{tikzpicture}'''.replace('PANEL',panel(key))
        with fitz.open(destination(key)/(key+'.pdf')) as doc:
            bars=[d['rect'] for d in doc[0].get_drawings() if d.get('fill') and (abs(d['fill'][0]-123/255)<1e-5 or abs(d['fill'][0]-200/255)<1e-5)]
            bars=sorted(bars,key=lambda r:r.y0)
            coords=[(88-57/2+r.x0*25.4/72-1,36+47/2-(r.y0+r.y1)/2*25.4/72) for r in bars]
        for color,original_y,bend,(x,y) in zip(['Blue','Red'],[42.5,31.5],[56,57],coords):
            replacement=chr(92)+'draw[foundation flow,draw=Figure'+color+'] (49,'+str(original_y)+')--('+str(bend)+','+str(original_y)+')--('+str(bend)+','+f'{y:.5f}'+')--('+f'{x:.5f},{y:.5f}'+');'
            s=re.sub(r'\\draw\[foundation flow,draw=Figure'+color+r'\].*?;',lambda m:replacement,s)
    elif key=='trust-conformal-construction':
        s=re.sub(r'figures/02-foundations/03-trustworthiness/matplotlib/trust-conformal-residuals.pdf',panel(key),s)
        s=s.replace('FigureYellowFill','FigureRedFill').replace('FigureYellow','FigureRed')
    elif key=='trust-dp-neighbors':
        s=s[:s.index(' \\fill[FigurePanel]')].replace('(0,-5)','(0,-12)')+r''' \node[inner sep=0pt] at (55,18) {\includegraphics[width=109mm]{PANEL}};
\end{tikzpicture}'''.replace('PANEL',panel(key))
    if key in {'learning-theory-curvature-stability','models-spatial-objectives','learning-theory-minimum-norm','trust-technical-scope','trust-robust-neighborhood','trust-certified-region','trust-actionable-recourse','trust-threat-model-coordinates'}:
        s=s.replace('FigureYellowFill','LancetGreen!12!white').replace('FigureYellow','LancetGreen')
    if key=='trust-certified-region':s=s.replace('rectangle (110,73)','rectangle (110,80)')
    if key in mixed:route='Matplotlib panels + TikZ composition'
    s=s.replace('✓',r'{\FigureMissingMathGlyphFont ✓}')
    d=destination(key);(d/'figure.tex').write_text(cleaned(s))
    records.append({'key':key,'route':route,'source':rel(d/'figure.tex'),'baseline_source':f['source'],'coordinate_data_preserved':True,'old_finished_images_used':False})
(OUT/'tikz-records.json').write_text(json.dumps(records,ensure_ascii=False,indent=2))
print('Editable TikZ figures:',len(records))
