#!/usr/bin/env python3
"""Reproduce the regression chapter's synthetic teaching examples.

Uses only the Python standard library. Run from the repository root:
    python3 figures/regression-examples.py
All x and y values are dimensionless; no data are empirical observations.
The regularization geometry and fixed regression tree are specified directly
in their editable TikZ sources.
"""

import csv
import math
from pathlib import Path


OUTPUT = Path(__file__).resolve().parent
OLS_X = list(range(7))
OLS_ERRORS = [0.6, -0.6, -0.4, 0.8, -0.4, -0.6, 0.6]
LOCAL_X = [0, 0.4, 0.9, 1.4, 2.1, 2.6, 2.9, 3.8, 4.8, 5.2, 6]
LOCAL_ERRORS = [-0.1, 0.15, -0.1, 0.2, -0.18, 0.1, -0.12, 0.15, -0.2, 0.12, -0.1]
QUERY = 2.8
NEIGHBORS = 4
BANDWIDTH = 1.2
GP_X = [-2.8, -2.2, -1.6, 0.6, 1.1, 2.7]
GP_Y = [-0.1, -0.5, -0.9, 0.65, 0.85, -0.2]
GP_LENGTH = 0.9
GP_SIGNAL_SD = 1.0
GP_NOISE_SD = 0.18


def save_csv(name, columns, rows):
    with (OUTPUT / name).open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow(columns)
        writer.writerows([[f"{v:.10g}" for v in row] for row in rows])


def fit_line(xs, ys, weights=None, center=0):
    weights = [1.0] * len(xs) if weights is None else weights
    us = [x - center for x in xs]
    s0 = sum(weights)
    s1 = sum(w * u for w, u in zip(weights, us))
    s2 = sum(w * u * u for w, u in zip(weights, us))
    t0 = sum(w * y for w, y in zip(weights, ys))
    t1 = sum(w * u * y for w, u, y in zip(weights, us, ys))
    determinant = s0 * s2 - s1 * s1
    if determinant <= 0:
        raise ValueError("The weighted design must have rank two.")
    return (s2 * t0 - s1 * t1) / determinant, (s0 * t1 - s1 * t0) / determinant


def cholesky(matrix):
    size = len(matrix)
    lower = [[0.0] * size for _ in range(size)]
    for i in range(size):
        for j in range(i + 1):
            remainder = matrix[i][j] - sum(lower[i][k] * lower[j][k] for k in range(j))
            lower[i][j] = math.sqrt(remainder) if i == j else remainder / lower[j][j]
    return lower


def forward_solve(lower, rhs):
    result = []
    for i, value in enumerate(rhs):
        result.append((value - sum(lower[i][j] * result[j] for j in range(i))) / lower[i][i])
    return result


def solve_from_cholesky(lower, rhs):
    intermediate = forward_solve(lower, rhs)
    result = [0.0] * len(rhs)
    for i in range(len(rhs) - 1, -1, -1):
        result[i] = (
            intermediate[i] - sum(lower[j][i] * result[j] for j in range(i + 1, len(rhs)))
        ) / lower[i][i]
    return result


def kernel(x, z):
    return GP_SIGNAL_SD**2 * math.exp(-0.5 * ((x - z) / GP_LENGTH) ** 2)


def main():
    ols_y = [1 + 0.5 * x + e for x, e in zip(OLS_X, OLS_ERRORS)]
    intercept, slope = fit_line(OLS_X, ols_y)
    assert math.isclose(intercept, 1.0, abs_tol=1e-12)
    assert math.isclose(slope, 0.5, abs_tol=1e-12)
    predictions = [intercept + slope * x for x in OLS_X]
    residuals = [y - fitted for y, fitted in zip(ols_y, predictions)]
    assert abs(sum(residuals)) < 1e-12
    assert abs(sum(x * r for x, r in zip(OLS_X, residuals))) < 1e-12
    save_csv("regression-ols.csv", ["x", "y", "fitted"], zip(OLS_X, ols_y, predictions))
    residual_source = ["% Generated by regression-examples.py; vertical response residuals."]
    for x, y, fitted in zip(OLS_X, ols_y, predictions):
        residual_source.append(
            rf"\draw[FigureLoss,densely dashed,line width=0.8pt] "
            rf"(axis cs:{x:.10g},{y:.10g})--(axis cs:{x:.10g},{fitted:.10g});"
        )
    (OUTPUT / "regression-ols-residuals.tex").write_text(
        "\n".join(residual_source) + "\n", encoding="utf-8"
    )

    local_y = [0.2 * x + 0.08 * x * x + e for x, e in zip(LOCAL_X, LOCAL_ERRORS)]
    nearest = sorted(range(len(LOCAL_X)), key=lambda i: (abs(LOCAL_X[i] - QUERY), i))[:NEIGHBORS]
    radius = max(abs(LOCAL_X[i] - QUERY) for i in nearest)
    knn = sum(local_y[i] for i in nearest) / NEIGHBORS
    weights = [
        (1 - abs((x - QUERY) / BANDWIDTH) ** 3) ** 3 if abs(x - QUERY) < BANDWIDTH else 0.0
        for x in LOCAL_X
    ]
    local_intercept, local_slope = fit_line(LOCAL_X, local_y, weights, QUERY)
    active = {i for i, w in enumerate(weights) if w > 0}
    assert set(nearest) == active  # The two panels use the same four observations.
    save_csv("regression-neighborhood.csv", ["x", "y"], zip(LOCAL_X, local_y))
    save_csv(
        "regression-neighborhood-selected.csv", ["x", "y"],
        [(LOCAL_X[i], local_y[i]) for i in sorted(active)]
    )
    query_values = {
        "RegressionQuery": QUERY,
        "RegressionKnnPrediction": knn,
        "RegressionKnnLeft": QUERY - radius,
        "RegressionKnnRight": QUERY + radius,
        "RegressionLocalLeft": QUERY - BANDWIDTH,
        "RegressionLocalRight": QUERY + BANDWIDTH,
        "RegressionLocalIntercept": local_intercept,
        "RegressionLocalSlope": local_slope,
    }
    (OUTPUT / "regression-neighborhood-values.tex").write_text(
        "% Generated by regression-examples.py.\n"
        + "\n".join(rf"\def\{key}{{{value:.10g}}}" for key, value in query_values.items()) + "\n",
        encoding="utf-8",
    )

    covariance = [
        [kernel(x, z) + (GP_NOISE_SD**2 if i == j else 0) for j, z in enumerate(GP_X)]
        for i, x in enumerate(GP_X)
    ]
    lower = cholesky(covariance)
    alpha = solve_from_cholesky(lower, GP_Y)
    assert max(
        abs(sum(covariance[i][j] * alpha[j] for j in range(len(GP_X))) - GP_Y[i])
        for i in range(len(GP_X))
    ) < 1e-12
    posterior = []
    for i in range(161):
        query = -4 + i * 0.05
        cross = [kernel(query, x) for x in GP_X]
        mean = sum(k * a for k, a in zip(cross, alpha))
        projected = forward_solve(lower, cross)
        variance = kernel(query, query) - sum(v * v for v in projected)
        assert -1e-12 <= variance <= GP_SIGNAL_SD**2 + 1e-12
        spread = 1.96 * math.sqrt(max(variance, 0.0))
        posterior.append((query, mean, mean - spread, mean + spread))
    save_csv("regression-gp-observations.csv", ["x", "y"], zip(GP_X, GP_Y))
    save_csv("regression-gp-posterior.csv", ["x", "mean", "lower", "upper"], posterior)
    band = [(r[0], r[3]) for r in posterior] + [(r[0], r[2]) for r in reversed(posterior)]
    save_csv("regression-gp-band.csv", ["x", "y"], band)
    print(f"OLS: intercept={intercept:.6f}, slope={slope:.6f}; both normal equations verified.")
    print(f"Neighborhood: x0={QUERY}, k={NEIGHBORS}, h={BANDWIDTH}, same four active samples.")
    print(f"Predictions: kNN={knn:.6f}, local linear={local_intercept:.6f}, slope={local_slope:.6f}.")
    print("GP: Cholesky solve residual and latent variance bounds verified on all 161 plot points.")


if __name__ == "__main__":
    main()
